# Proxy 24 配置文件
whitelist:
  # 白名单域名列表，每行一个域名
  - baidu.com
  - microsoft.com
  - microsoftonline.com
  - bing.com
  - baiduapis.com
  - baidustatic.com
  - baidustatic.com
  - 360.com
  - 360.net
  - sougou.com
  - quark.cn
  - effirst.com
  - googleapis.com
  - aliapp.org
  - bdstatic.co
  - sm.cn
  - qq.com
  - qq.net
  - qq.cn
  - weixin.com
  - weixin.net
  - weixin.qq.com
  - weixin.qq.net
  - weixin.qq.cn
  - tongyi.com
  - taobao.com
  - tmall.com
  - alipay.com
  - 163.com
  - sina.com.cn
  - weibo.com
  - jd.com
  - youku.com
  - tudou.com
  - bilibili.com
  - iqiyi.com
  - sohu.com
  - cctv.com
  - zhihu.com
  - cnblogs.com
  - csdn.net
  - sogou.com
  - 360.cn
  - huawei.com